// Calisthenics knowledge base. Bodyweight progressions, isometrics, gymnastic
// strength elements. Anything that lives off a barbell.

import type { ExerciseEntry } from './types';

export const CALISTHENICS_EXERCISES: ExerciseEntry[] = [
  {
    id: 'dip',
    name: 'Fondos en paralelas',
    aliases: ['dip', 'parallel bar dip'],
    disciplines: ['calisthenics', 'strength'],
    pattern: 'horizontal_push',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['shoulders_front'],
    equipment: ['parallettes', 'bodyweight'],
    minLevel: 'intermediate',
    progressions: ['weighted_dip', 'ring_dip'],
    regressions: ['bench_dip'],
    contraindications: ['shoulder_pain'],
    naturalMetrics: ['reps', 'weight'],
  },
  {
    id: 'bench_dip',
    name: 'Fondos en banco',
    aliases: ['bench dip'],
    disciplines: ['calisthenics'],
    pattern: 'horizontal_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders_front'],
    equipment: ['bench', 'bodyweight'],
    minLevel: 'beginner',
    progressions: ['dip'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'weighted_dip',
    name: 'Fondos con lastre',
    aliases: ['weighted dip'],
    disciplines: ['calisthenics'],
    pattern: 'horizontal_push',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['shoulders_front'],
    equipment: ['parallettes'],
    minLevel: 'advanced',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'ring_dip',
    name: 'Fondos en anillas',
    aliases: ['ring dip'],
    disciplines: ['calisthenics'],
    pattern: 'horizontal_push',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['shoulders_front', 'core'],
    equipment: ['rings'],
    minLevel: 'advanced',
    naturalMetrics: ['reps'],
  },
  {
    id: 'l_sit',
    name: 'L-sit',
    aliases: ['l sit'],
    disciplines: ['calisthenics'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core', 'hip_flexors'],
    secondaryMuscles: ['triceps', 'shoulders_front'],
    equipment: ['parallettes', 'bodyweight'],
    minLevel: 'intermediate',
    progressions: ['v_sit'],
    regressions: ['tuck_l_sit'],
    naturalMetrics: ['time'],
  },
  {
    id: 'tuck_l_sit',
    name: 'Tuck L-sit',
    aliases: ['tuck l-sit'],
    disciplines: ['calisthenics'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core'],
    secondaryMuscles: ['hip_flexors'],
    equipment: ['parallettes', 'bodyweight'],
    minLevel: 'beginner',
    progressions: ['l_sit'],
    naturalMetrics: ['time'],
  },
  {
    id: 'v_sit',
    name: 'V-sit',
    aliases: ['v sit'],
    disciplines: ['calisthenics'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core', 'hip_flexors'],
    secondaryMuscles: ['triceps'],
    equipment: ['parallettes'],
    minLevel: 'advanced',
    naturalMetrics: ['time'],
  },
  {
    id: 'plank',
    name: 'Plancha frontal',
    aliases: ['plank'],
    disciplines: ['calisthenics', 'mobility', 'strength'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders_front', 'glutes'],
    equipment: ['bodyweight', 'yoga_mat'],
    minLevel: 'beginner',
    progressions: ['rkc_plank', 'plank_to_pushup'],
    naturalMetrics: ['time'],
    tags: ['warmup', 'home_friendly'],
  },
  {
    id: 'rkc_plank',
    name: 'Plancha RKC',
    aliases: ['rkc plank'],
    disciplines: ['calisthenics', 'strength'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    minLevel: 'intermediate',
    naturalMetrics: ['time'],
  },
  {
    id: 'side_plank',
    name: 'Plancha lateral',
    aliases: ['side plank'],
    disciplines: ['calisthenics', 'mobility'],
    pattern: 'core_anti_rotation',
    primaryMuscles: ['obliques', 'core'],
    secondaryMuscles: ['shoulders_side'],
    equipment: ['bodyweight', 'yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['time'],
  },
  {
    id: 'hollow_hold',
    name: 'Hollow body hold',
    aliases: ['hollow hold', 'hollow body'],
    disciplines: ['calisthenics'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core'],
    secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight', 'yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['time'],
  },
  {
    id: 'hanging_leg_raise',
    name: 'Elevación de piernas en barra',
    aliases: ['hanging leg raise'],
    disciplines: ['calisthenics'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core', 'hip_flexors'],
    secondaryMuscles: ['forearms'],
    equipment: ['pull_up_bar'],
    minLevel: 'intermediate',
    regressions: ['hanging_knee_raise'],
    progressions: ['toes_to_bar'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'hanging_knee_raise',
    name: 'Elevación de rodillas en barra',
    aliases: ['hanging knee raise'],
    disciplines: ['calisthenics'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core', 'hip_flexors'],
    secondaryMuscles: [],
    equipment: ['pull_up_bar'],
    minLevel: 'beginner',
    progressions: ['hanging_leg_raise'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'toes_to_bar',
    name: 'Toes to bar',
    aliases: ['toes to bar', 't2b'],
    disciplines: ['calisthenics'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core', 'hip_flexors'],
    secondaryMuscles: ['back_lats'],
    equipment: ['pull_up_bar'],
    minLevel: 'advanced',
    naturalMetrics: ['reps'],
  },
  {
    id: 'mountain_climber',
    name: 'Mountain climbers',
    aliases: ['mountain climber'],
    disciplines: ['calisthenics'],
    pattern: 'plyometric',
    primaryMuscles: ['core', 'shoulders_front'],
    secondaryMuscles: ['quads', 'cardiovascular'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'time'],
    tags: ['conditioning', 'warmup'],
  },
  {
    id: 'burpee',
    name: 'Burpee',
    aliases: ['burpee'],
    disciplines: ['calisthenics', 'general'],
    pattern: 'plyometric',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['cardiovascular'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'time'],
    tags: ['conditioning'],
  },
  {
    id: 'jumping_jack',
    name: 'Jumping jacks',
    aliases: ['jumping jack'],
    disciplines: ['calisthenics', 'general'],
    pattern: 'plyometric',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['calves', 'shoulders_side'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'time'],
    tags: ['warmup'],
  },
  {
    id: 'box_jump',
    name: 'Salto al cajón',
    aliases: ['box jump'],
    disciplines: ['calisthenics', 'general'],
    pattern: 'plyometric',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['core'],
    equipment: ['box'],
    minLevel: 'intermediate',
    contraindications: ['knee_pain'],
    naturalMetrics: ['reps'],
    tags: ['power'],
  },
  {
    id: 'jumping_squat',
    name: 'Sentadilla con salto',
    aliases: ['jump squat'],
    disciplines: ['calisthenics'],
    pattern: 'plyometric',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'time'],
  },
  {
    id: 'muscle_up',
    name: 'Muscle-up',
    aliases: ['muscle up'],
    disciplines: ['calisthenics'],
    pattern: 'vertical_pull',
    primaryMuscles: ['back_lats', 'triceps', 'chest'],
    secondaryMuscles: ['core', 'forearms'],
    equipment: ['pull_up_bar', 'rings'],
    minLevel: 'advanced',
    regressions: ['weighted_pullup'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'human_flag_progression',
    name: 'Human flag (progresión)',
    aliases: ['human flag'],
    disciplines: ['calisthenics'],
    pattern: 'core_anti_rotation',
    primaryMuscles: ['core', 'obliques', 'shoulders_side'],
    secondaryMuscles: ['back_lats'],
    equipment: ['pull_up_bar'],
    minLevel: 'advanced',
    naturalMetrics: ['time'],
  },
  {
    id: 'wall_handstand_hold',
    name: 'Pino contra pared',
    aliases: ['wall handstand', 'handstand hold'],
    disciplines: ['calisthenics', 'mobility'],
    pattern: 'vertical_push',
    primaryMuscles: ['shoulders_front', 'core'],
    secondaryMuscles: ['triceps'],
    equipment: ['bodyweight'],
    minLevel: 'intermediate',
    naturalMetrics: ['time'],
  },
];
