// Endurance / cardio knowledge base. Running, cycling, rowing, swimming,
// HIIT formats. Sport-specific drills live in sport_specific.ts.

import type { ExerciseEntry } from './types';

export const ENDURANCE_EXERCISES: ExerciseEntry[] = [
  // ======== RUNNING ========
  {
    id: 'easy_run',
    name: 'Carrera continua suave',
    aliases: ['easy run', 'rodaje suave'],
    disciplines: ['running'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular', 'quads', 'calves'],
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: ['open_space'],
    minLevel: 'beginner',
    naturalMetrics: ['distance', 'time', 'pace', 'heart_rate'],
    tags: ['zone_2'],
    cue: 'Cadencia ~170-180 ppm, respiración cómoda, capaz de mantener conversación.',
  },
  {
    id: 'tempo_run',
    name: 'Carrera tempo / umbral',
    aliases: ['tempo run', 'threshold run'],
    disciplines: ['running'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['quads', 'calves'],
    equipment: ['open_space'],
    minLevel: 'intermediate',
    naturalMetrics: ['distance', 'time', 'pace', 'heart_rate'],
  },
  {
    id: 'interval_400',
    name: 'Series de 400m',
    aliases: ['400m intervals'],
    disciplines: ['running'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular', 'quads'],
    secondaryMuscles: ['calves', 'glutes'],
    equipment: ['open_space'],
    minLevel: 'intermediate',
    naturalMetrics: ['distance', 'time', 'pace', 'rounds'],
  },
  {
    id: 'interval_1k',
    name: 'Series de 1km',
    aliases: ['1k intervals'],
    disciplines: ['running'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular', 'quads'],
    secondaryMuscles: ['calves'],
    equipment: ['open_space'],
    minLevel: 'intermediate',
    naturalMetrics: ['distance', 'time', 'pace'],
  },
  {
    id: 'fartlek',
    name: 'Fartlek',
    aliases: ['fartlek'],
    disciplines: ['running'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['quads'],
    equipment: ['open_space'],
    minLevel: 'beginner',
    naturalMetrics: ['time', 'distance', 'heart_rate'],
  },
  {
    id: 'hill_repeat',
    name: 'Cuestas',
    aliases: ['hill repeats', 'hill sprints'],
    disciplines: ['running'],
    pattern: 'locomotion',
    primaryMuscles: ['quads', 'glutes', 'cardiovascular'],
    secondaryMuscles: ['calves'],
    equipment: ['open_space'],
    minLevel: 'intermediate',
    naturalMetrics: ['rounds', 'time'],
  },
  {
    id: 'long_run',
    name: 'Tirada larga',
    aliases: ['long run'],
    disciplines: ['running'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: ['quads', 'glutes', 'calves'],
    equipment: ['open_space'],
    minLevel: 'beginner',
    naturalMetrics: ['distance', 'time', 'pace'],
  },
  {
    id: 'walking',
    name: 'Caminar',
    aliases: ['walking', 'caminata'],
    disciplines: ['general', 'running'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular'],
    secondaryMuscles: [],
    equipment: ['open_space'],
    minLevel: 'beginner',
    naturalMetrics: ['distance', 'time'],
    tags: ['recovery', 'warmup'],
  },

  // ======== CYCLING ========
  {
    id: 'cycling_endurance',
    name: 'Bici fondo aeróbico',
    aliases: ['endurance ride', 'z2 bike'],
    disciplines: ['cycling'],
    pattern: 'locomotion',
    primaryMuscles: ['quads', 'cardiovascular'],
    secondaryMuscles: ['glutes', 'calves'],
    equipment: ['bike'],
    minLevel: 'beginner',
    naturalMetrics: ['distance', 'time', 'heart_rate'],
  },
  {
    id: 'cycling_intervals',
    name: 'Intervalos en bici',
    aliases: ['cycling intervals'],
    disciplines: ['cycling'],
    pattern: 'locomotion',
    primaryMuscles: ['quads', 'cardiovascular'],
    secondaryMuscles: ['glutes'],
    equipment: ['bike'],
    minLevel: 'intermediate',
    naturalMetrics: ['time', 'rounds', 'heart_rate'],
  },

  // ======== ROWING ========
  {
    id: 'rowing_steady',
    name: 'Remo continuo',
    aliases: ['steady rowing'],
    disciplines: ['general'],
    pattern: 'locomotion',
    primaryMuscles: ['back_lats', 'quads', 'cardiovascular'],
    secondaryMuscles: ['core', 'biceps'],
    equipment: ['rower'],
    minLevel: 'beginner',
    naturalMetrics: ['distance', 'time', 'cadence'],
  },
  {
    id: 'rowing_intervals',
    name: 'Intervalos de remo',
    aliases: ['rowing intervals'],
    disciplines: ['general'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular', 'back_lats', 'quads'],
    secondaryMuscles: ['core'],
    equipment: ['rower'],
    minLevel: 'intermediate',
    naturalMetrics: ['rounds', 'distance', 'time'],
  },

  // ======== SWIMMING ========
  {
    id: 'swim_freestyle',
    name: 'Crol técnica',
    aliases: ['freestyle swim'],
    disciplines: ['swimming'],
    pattern: 'locomotion',
    primaryMuscles: ['back_lats', 'cardiovascular', 'shoulders_front'],
    secondaryMuscles: ['core'],
    equipment: ['pool'],
    minLevel: 'beginner',
    naturalMetrics: ['distance', 'time'],
  },
  {
    id: 'swim_intervals_50',
    name: 'Series de 50m',
    aliases: ['50m swim intervals'],
    disciplines: ['swimming'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular', 'back_lats'],
    secondaryMuscles: ['shoulders_front', 'core'],
    equipment: ['pool'],
    minLevel: 'intermediate',
    naturalMetrics: ['rounds', 'time'],
  },

  // ======== HIIT FORMATS ========
  {
    id: 'tabata_block',
    name: 'Tabata (8 rondas)',
    aliases: ['tabata'],
    disciplines: ['general', 'calisthenics'],
    pattern: 'plyometric',
    primaryMuscles: ['cardiovascular', 'full_body'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    minLevel: 'intermediate',
    naturalMetrics: ['rounds', 'time'],
    tags: ['hiit'],
    cue: '20s trabajo / 10s descanso · 8 rondas · una sola intensidad alta.',
  },
  {
    id: 'emom_10',
    name: 'EMOM 10 minutos',
    aliases: ['emom'],
    disciplines: ['general'],
    pattern: 'plyometric',
    primaryMuscles: ['cardiovascular', 'full_body'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    minLevel: 'intermediate',
    naturalMetrics: ['rounds', 'time'],
    tags: ['hiit'],
  },
  {
    id: 'amrap_15',
    name: 'AMRAP 15 minutos',
    aliases: ['amrap'],
    disciplines: ['general'],
    pattern: 'plyometric',
    primaryMuscles: ['cardiovascular', 'full_body'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    minLevel: 'intermediate',
    naturalMetrics: ['rounds', 'time'],
    tags: ['hiit'],
  },

  // ======== JUMP ROPE ========
  {
    id: 'jump_rope_basic',
    name: 'Saltar a la cuerda',
    aliases: ['jump rope', 'skipping'],
    disciplines: ['general', 'calisthenics'],
    pattern: 'plyometric',
    primaryMuscles: ['calves', 'cardiovascular'],
    secondaryMuscles: ['shoulders_front', 'forearms'],
    equipment: ['jump_rope'],
    minLevel: 'beginner',
    naturalMetrics: ['time', 'reps', 'rounds'],
    tags: ['warmup', 'conditioning'],
  },
];
