// Mobility / yoga / activation knowledge base. The drills the AI reaches for
// when building warmups, cooldowns, or dedicated mobility blocks.

import type { ExerciseEntry } from './types';

export const MOBILITY_EXERCISES: ExerciseEntry[] = [
  {
    id: 'world_greatest_stretch',
    name: 'World’s greatest stretch',
    aliases: ['worlds greatest stretch'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['hip_flexors', 'hamstrings', 'shoulders_front'],
    secondaryMuscles: ['core', 'back_upper'],
    equipment: ['bodyweight', 'yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'time'],
    tags: ['warmup', 'full_body'],
  },
  {
    id: 'cat_cow',
    name: 'Cat-cow',
    aliases: ['cat cow', 'gato-vaca'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['back_lower', 'back_upper', 'core'],
    secondaryMuscles: [],
    equipment: ['yoga_mat', 'bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'time'],
    tags: ['warmup', 'spine'],
  },
  {
    id: 'thoracic_rotation',
    name: 'Rotación torácica en cuadrupedia',
    aliases: ['thoracic rotation', 't-spine rotation'],
    disciplines: ['mobility'],
    pattern: 'rotation',
    primaryMuscles: ['back_upper'],
    secondaryMuscles: ['obliques'],
    equipment: ['bodyweight', 'yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['reps'],
    tags: ['warmup', 'spine'],
  },
  {
    id: 'pigeon_pose',
    name: 'Postura de la paloma',
    aliases: ['pigeon pose'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['glutes', 'hip_flexors'],
    secondaryMuscles: ['adductors'],
    equipment: ['yoga_mat', 'bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['time'],
    tags: ['cooldown', 'hips'],
  },
  {
    id: 'couch_stretch',
    name: 'Couch stretch',
    aliases: ['couch stretch'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['hip_flexors', 'quads'],
    secondaryMuscles: [],
    equipment: ['yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['time'],
  },
  {
    id: '90_90_hip',
    name: '90/90 cadera',
    aliases: ['90 90 hip'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['hip_flexors', 'glutes'],
    secondaryMuscles: ['adductors'],
    equipment: ['yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['time', 'reps'],
  },
  {
    id: 'downward_dog',
    name: 'Perro boca abajo',
    aliases: ['downward dog'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['hamstrings', 'calves', 'shoulders_front'],
    secondaryMuscles: ['back_lats', 'core'],
    equipment: ['yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['time'],
    tags: ['yoga', 'cooldown'],
  },
  {
    id: 'child_pose',
    name: 'Postura del niño',
    aliases: ['child pose', 'balasana'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['back_lower'],
    secondaryMuscles: ['shoulders_front'],
    equipment: ['yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['time'],
    tags: ['cooldown', 'yoga'],
  },
  {
    id: 'cobra',
    name: 'Cobra',
    aliases: ['cobra pose'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['back_lower', 'back_upper'],
    secondaryMuscles: ['shoulders_front'],
    equipment: ['yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['time', 'reps'],
  },
  {
    id: 'sun_salutation_a',
    name: 'Saludo al sol A',
    aliases: ['sun salutation a', 'surya namaskar'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['cardiovascular'],
    equipment: ['yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['rounds', 'time'],
    tags: ['yoga', 'warmup'],
  },
  {
    id: 'shoulder_dislocates',
    name: 'Dislocations de hombro con banda',
    aliases: ['shoulder dislocates', 'pass-throughs'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['shoulders_front', 'shoulders_rear'],
    secondaryMuscles: ['back_upper'],
    equipment: ['resistance_bands'],
    minLevel: 'beginner',
    naturalMetrics: ['reps'],
    tags: ['warmup', 'shoulder_health'],
  },
  {
    id: 'banded_pull_apart',
    name: 'Pull apart con banda',
    aliases: ['band pull apart'],
    disciplines: ['mobility', 'strength'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['shoulders_rear', 'back_upper'],
    secondaryMuscles: [],
    equipment: ['resistance_bands'],
    minLevel: 'beginner',
    naturalMetrics: ['reps'],
    tags: ['shoulder_health', 'warmup'],
  },
  {
    id: 'foam_roll_quads',
    name: 'Foam rolling cuádriceps',
    aliases: ['foam roller quads'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['foam_roller'],
    minLevel: 'beginner',
    naturalMetrics: ['time'],
    tags: ['recovery'],
  },
  {
    id: 'foam_roll_back',
    name: 'Foam rolling espalda alta',
    aliases: ['foam roller upper back'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['back_upper'],
    secondaryMuscles: [],
    equipment: ['foam_roller'],
    minLevel: 'beginner',
    naturalMetrics: ['time'],
    tags: ['recovery'],
  },
  {
    id: 'ankle_circles',
    name: 'Círculos de tobillo',
    aliases: ['ankle circles'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'time'],
    tags: ['warmup'],
  },
  {
    id: 'leg_swing',
    name: 'Balanceos de pierna',
    aliases: ['leg swings'],
    disciplines: ['mobility'],
    pattern: 'mobility',
    primaryMuscles: ['hip_flexors', 'hamstrings'],
    secondaryMuscles: ['adductors'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['reps'],
    tags: ['warmup'],
  },
  {
    id: 'dead_bug',
    name: 'Dead bug',
    aliases: ['dead bug'],
    disciplines: ['mobility', 'strength'],
    pattern: 'core_anti_extension',
    primaryMuscles: ['core'],
    secondaryMuscles: ['hip_flexors'],
    equipment: ['yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['reps'],
    tags: ['warmup', 'rehab'],
  },
  {
    id: 'birddog',
    name: 'Bird-dog',
    aliases: ['birddog'],
    disciplines: ['mobility', 'strength'],
    pattern: 'core_anti_rotation',
    primaryMuscles: ['core', 'glutes'],
    secondaryMuscles: ['back_lower'],
    equipment: ['yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['reps'],
    tags: ['warmup', 'rehab'],
  },
];
