// Sport-specific drills. Football (soccer), basketball, tennis, climbing,
// surfing — anything that benefits from targeted prep work outside the gym.

import type { ExerciseEntry } from './types';

export const SPORT_EXERCISES: ExerciseEntry[] = [
  // ======== FOOTBALL / SOCCER ========
  {
    id: 'cone_dribble',
    name: 'Conducción entre conos',
    aliases: ['cone dribble', 'dribbling drill'],
    disciplines: ['team_sport'],
    pattern: 'sport_skill',
    primaryMuscles: ['quads', 'cardiovascular'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['ball', 'open_space'],
    minLevel: 'beginner',
    naturalMetrics: ['rounds', 'time'],
    tags: ['football', 'agility'],
  },
  {
    id: 'shuttle_run',
    name: 'Sprints de ida y vuelta',
    aliases: ['shuttle run'],
    disciplines: ['team_sport', 'general'],
    pattern: 'locomotion',
    primaryMuscles: ['cardiovascular', 'quads'],
    secondaryMuscles: ['calves'],
    equipment: ['open_space'],
    minLevel: 'beginner',
    naturalMetrics: ['rounds', 'time'],
    tags: ['agility', 'football', 'basketball'],
  },
  {
    id: 'lateral_bound',
    name: 'Saltos laterales',
    aliases: ['lateral bound'],
    disciplines: ['team_sport'],
    pattern: 'plyometric',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['core', 'abductors'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['reps'],
    tags: ['agility'],
  },
  {
    id: 'nordic_hamstring',
    name: 'Curl nórdico',
    aliases: ['nordic hamstring curl'],
    disciplines: ['team_sport', 'strength'],
    pattern: 'isolation',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    minLevel: 'intermediate',
    naturalMetrics: ['reps'],
    tags: ['injury_prevention', 'football'],
  },
  {
    id: 'copenhagen_plank',
    name: 'Plancha Copenhagen',
    aliases: ['copenhagen plank'],
    disciplines: ['team_sport', 'strength'],
    pattern: 'core_anti_rotation',
    primaryMuscles: ['adductors', 'core'],
    secondaryMuscles: ['obliques'],
    equipment: ['bench', 'yoga_mat'],
    minLevel: 'intermediate',
    naturalMetrics: ['time'],
    tags: ['injury_prevention', 'football'],
  },

  // ======== BASKETBALL ========
  {
    id: 'depth_jump',
    name: 'Salto en profundidad',
    aliases: ['depth jump'],
    disciplines: ['team_sport'],
    pattern: 'plyometric',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['core'],
    equipment: ['box'],
    minLevel: 'advanced',
    contraindications: ['knee_pain', 'ankle_pain'],
    naturalMetrics: ['reps'],
    tags: ['power', 'basketball'],
  },
  {
    id: 'broad_jump',
    name: 'Salto horizontal',
    aliases: ['broad jump', 'standing long jump'],
    disciplines: ['team_sport'],
    pattern: 'plyometric',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'distance'],
    tags: ['power'],
  },

  // ======== CLIMBING ========
  {
    id: 'dead_hang',
    name: 'Suspensión pasiva en barra',
    aliases: ['dead hang'],
    disciplines: ['calisthenics'],
    pattern: 'isolation',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['back_lats', 'shoulders_front'],
    equipment: ['pull_up_bar'],
    minLevel: 'beginner',
    naturalMetrics: ['time'],
    tags: ['grip', 'climbing'],
  },
  {
    id: 'scapular_pullup',
    name: 'Scapular pull-up',
    aliases: ['scapular pull-up', 'scap pull up'],
    disciplines: ['calisthenics'],
    pattern: 'vertical_pull',
    primaryMuscles: ['back_lats', 'back_upper'],
    secondaryMuscles: [],
    equipment: ['pull_up_bar'],
    minLevel: 'beginner',
    progressions: ['pullup'],
    naturalMetrics: ['reps'],
    tags: ['climbing', 'shoulder_health'],
  },
  {
    id: 'finger_hangs',
    name: 'Suspensiones en regletas (fingerboard)',
    aliases: ['finger hang', 'hangboard'],
    disciplines: ['calisthenics'],
    pattern: 'isolation',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['back_lats'],
    equipment: ['pull_up_bar'],
    minLevel: 'advanced',
    contraindications: ['finger_pulley_injury'],
    naturalMetrics: ['time', 'rounds'],
    tags: ['climbing', 'grip'],
  },

  // ======== TENNIS / RACKET ========
  {
    id: 'medicine_ball_slam',
    name: 'Slam con balón medicinal',
    aliases: ['med ball slam'],
    disciplines: ['team_sport', 'general'],
    pattern: 'rotation',
    primaryMuscles: ['core', 'back_lats'],
    secondaryMuscles: ['shoulders_front', 'cardiovascular'],
    equipment: ['medicine_ball'],
    minLevel: 'beginner',
    naturalMetrics: ['reps'],
    tags: ['power', 'rotation'],
  },
  {
    id: 'medicine_ball_rotation_throw',
    name: 'Lanzamiento rotacional con balón medicinal',
    aliases: ['med ball rotation throw'],
    disciplines: ['team_sport'],
    pattern: 'rotation',
    primaryMuscles: ['obliques', 'core'],
    secondaryMuscles: ['shoulders_front'],
    equipment: ['medicine_ball'],
    minLevel: 'intermediate',
    naturalMetrics: ['reps'],
    tags: ['rotation', 'tennis', 'golf'],
  },

  // ======== SURFING / WATER SPORTS ========
  {
    id: 'pop_up_drill',
    name: 'Pop-up de tabla',
    aliases: ['pop up surf drill'],
    disciplines: ['team_sport'],
    pattern: 'plyometric',
    primaryMuscles: ['core', 'shoulders_front', 'quads'],
    secondaryMuscles: [],
    equipment: ['yoga_mat'],
    minLevel: 'beginner',
    naturalMetrics: ['reps'],
    tags: ['surfing'],
  },
  {
    id: 'paddling_simulation',
    name: 'Simulación de remada',
    aliases: ['paddle sim'],
    disciplines: ['team_sport'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['back_lats', 'shoulders_rear'],
    secondaryMuscles: ['cardiovascular'],
    equipment: ['resistance_bands'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'time'],
    tags: ['surfing'],
  },
];
