// Strength knowledge base. Curated entries focused on classic gym + home
// strength training. Names are Spanish-first; aliases include English + common
// variants so the user prompt matches even when the model asks "bench press".

import type { ExerciseEntry } from './types';

export const STRENGTH_EXERCISES: ExerciseEntry[] = [
  // ======== HORIZONTAL PUSH ========
  {
    id: 'bench_press',
    name: 'Press de banca con barra',
    aliases: ['bench press', 'barbell bench press', 'press banca'],
    disciplines: ['strength'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders_front'],
    equipment: ['barbell_plates', 'bench'],
    minLevel: 'intermediate',
    progressions: ['close_grip_bench', 'incline_bench_press'],
    regressions: ['db_bench_press', 'pushup'],
    contraindications: ['shoulder_pain'],
    naturalMetrics: ['weight', 'reps', 'rir'],
    tags: ['compound', 'main_lift'],
    cue: 'Escápulas retraídas, codos a 60° del torso, barra al esternón.',
  },
  {
    id: 'db_bench_press',
    name: 'Press banca con mancuernas',
    aliases: ['dumbbell bench press', 'db bench'],
    disciplines: ['strength'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders_front'],
    equipment: ['dumbbells', 'bench'],
    minLevel: 'beginner',
    progressions: ['bench_press', 'incline_db_bench'],
    regressions: ['pushup'],
    naturalMetrics: ['weight', 'reps'],
    tags: ['compound'],
  },
  {
    id: 'incline_db_bench',
    name: 'Press inclinado con mancuernas',
    aliases: ['incline dumbbell press'],
    disciplines: ['strength'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest', 'shoulders_front'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'incline_bench_press',
    name: 'Press inclinado con barra',
    aliases: ['incline bench press'],
    disciplines: ['strength'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest', 'shoulders_front'],
    secondaryMuscles: ['triceps'],
    equipment: ['barbell_plates', 'bench'],
    minLevel: 'intermediate',
    naturalMetrics: ['weight', 'reps', 'rir'],
  },
  {
    id: 'close_grip_bench',
    name: 'Press de banca agarre cerrado',
    aliases: ['close grip bench press'],
    disciplines: ['strength'],
    pattern: 'horizontal_push',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['shoulders_front'],
    equipment: ['barbell_plates', 'bench'],
    minLevel: 'intermediate',
    naturalMetrics: ['weight', 'reps', 'rir'],
  },
  {
    id: 'pushup',
    name: 'Flexiones',
    aliases: ['push-up', 'push up', 'flexion', 'flexiones'],
    disciplines: ['strength', 'calisthenics'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders_front', 'core'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    progressions: ['decline_pushup', 'archer_pushup', 'one_arm_pushup'],
    regressions: ['knee_pushup', 'incline_pushup'],
    naturalMetrics: ['reps', 'rpe'],
    tags: ['compound', 'home_friendly'],
  },
  {
    id: 'incline_pushup',
    name: 'Flexiones inclinadas',
    aliases: ['incline push-up'],
    disciplines: ['strength', 'calisthenics'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight', 'box'],
    minLevel: 'beginner',
    progressions: ['pushup'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'decline_pushup',
    name: 'Flexiones declinadas',
    aliases: ['decline push-up'],
    disciplines: ['strength', 'calisthenics'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest', 'shoulders_front'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['bodyweight', 'box'],
    minLevel: 'intermediate',
    progressions: ['archer_pushup'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'archer_pushup',
    name: 'Flexiones de arquero',
    aliases: ['archer push-up'],
    disciplines: ['calisthenics', 'strength'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders_front', 'core'],
    equipment: ['bodyweight'],
    minLevel: 'advanced',
    regressions: ['decline_pushup'],
    progressions: ['one_arm_pushup'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'one_arm_pushup',
    name: 'Flexión a una mano',
    aliases: ['one-arm push-up'],
    disciplines: ['calisthenics'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps', 'core'],
    secondaryMuscles: ['shoulders_front', 'obliques'],
    equipment: ['bodyweight'],
    minLevel: 'advanced',
    regressions: ['archer_pushup'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'knee_pushup',
    name: 'Flexiones con rodillas apoyadas',
    aliases: ['knee push-up'],
    disciplines: ['strength', 'calisthenics'],
    pattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders_front'],
    equipment: ['bodyweight', 'yoga_mat'],
    minLevel: 'beginner',
    progressions: ['pushup'],
    naturalMetrics: ['reps'],
  },

  // ======== VERTICAL PUSH ========
  {
    id: 'overhead_press',
    name: 'Press militar con barra',
    aliases: ['overhead press', 'ohp', 'press militar'],
    disciplines: ['strength'],
    pattern: 'vertical_push',
    primaryMuscles: ['shoulders_front', 'shoulders_side'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['barbell_plates'],
    minLevel: 'intermediate',
    progressions: ['push_press'],
    regressions: ['db_shoulder_press'],
    contraindications: ['shoulder_pain'],
    naturalMetrics: ['weight', 'reps', 'rir'],
    tags: ['compound'],
    cue: 'Glúteos apretados, costillas hacia abajo, barra sobre la mitad del pie.',
  },
  {
    id: 'db_shoulder_press',
    name: 'Press de hombros con mancuernas',
    aliases: ['dumbbell shoulder press', 'seated db press'],
    disciplines: ['strength'],
    pattern: 'vertical_push',
    primaryMuscles: ['shoulders_front', 'shoulders_side'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'arnold_press',
    name: 'Press Arnold',
    aliases: ['arnold press'],
    disciplines: ['strength'],
    pattern: 'vertical_push',
    primaryMuscles: ['shoulders_front', 'shoulders_side'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells'],
    minLevel: 'intermediate',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'pike_pushup',
    name: 'Pike push-up',
    aliases: ['pike push-up'],
    disciplines: ['calisthenics'],
    pattern: 'vertical_push',
    primaryMuscles: ['shoulders_front'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    progressions: ['handstand_pushup_negative'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'handstand_pushup_negative',
    name: 'Negativos handstand push-up',
    aliases: ['hspu negative'],
    disciplines: ['calisthenics'],
    pattern: 'vertical_push',
    primaryMuscles: ['shoulders_front', 'triceps'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    minLevel: 'advanced',
    regressions: ['pike_pushup'],
    naturalMetrics: ['reps', 'time'],
  },
  {
    id: 'lateral_raise',
    name: 'Elevaciones laterales',
    aliases: ['lateral raise', 'side raise'],
    disciplines: ['strength'],
    pattern: 'isolation',
    primaryMuscles: ['shoulders_side'],
    secondaryMuscles: [],
    equipment: ['dumbbells'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
    tags: ['isolation'],
  },
  {
    id: 'rear_delt_fly',
    name: 'Pájaros (rear delt fly)',
    aliases: ['rear delt fly', 'reverse fly'],
    disciplines: ['strength'],
    pattern: 'isolation',
    primaryMuscles: ['shoulders_rear'],
    secondaryMuscles: ['back_upper'],
    equipment: ['dumbbells'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
    tags: ['isolation'],
  },

  // ======== HORIZONTAL PULL ========
  {
    id: 'barbell_row',
    name: 'Remo con barra',
    aliases: ['barbell row', 'bent over row'],
    disciplines: ['strength'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['back_lats', 'back_upper'],
    secondaryMuscles: ['biceps', 'back_lower'],
    equipment: ['barbell_plates'],
    minLevel: 'intermediate',
    contraindications: ['lower_back_pain'],
    naturalMetrics: ['weight', 'reps', 'rir'],
    tags: ['compound'],
  },
  {
    id: 'db_row',
    name: 'Remo con mancuerna a una mano',
    aliases: ['dumbbell row', 'one arm db row'],
    disciplines: ['strength'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['back_lats'],
    secondaryMuscles: ['biceps', 'back_upper'],
    equipment: ['dumbbells', 'bench'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'inverted_row',
    name: 'Remo invertido',
    aliases: ['inverted row', 'australian pull-up'],
    disciplines: ['calisthenics', 'strength'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['back_lats', 'back_upper'],
    secondaryMuscles: ['biceps', 'core'],
    equipment: ['bodyweight', 'pull_up_bar'],
    minLevel: 'beginner',
    progressions: ['pullup'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'seated_cable_row',
    name: 'Remo sentado en polea',
    aliases: ['seated cable row'],
    disciplines: ['strength'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['back_lats', 'back_upper'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'face_pull',
    name: 'Face pull',
    aliases: ['face pull'],
    disciplines: ['strength'],
    pattern: 'horizontal_pull',
    primaryMuscles: ['shoulders_rear', 'back_upper'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable', 'resistance_bands'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
    tags: ['shoulder_health'],
  },

  // ======== VERTICAL PULL ========
  {
    id: 'pullup',
    name: 'Dominadas',
    aliases: ['pull-up', 'pullup', 'pull up'],
    disciplines: ['calisthenics', 'strength'],
    pattern: 'vertical_pull',
    primaryMuscles: ['back_lats'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['pull_up_bar'],
    minLevel: 'intermediate',
    progressions: ['weighted_pullup', 'archer_pullup'],
    regressions: ['negative_pullup', 'banded_pullup', 'inverted_row'],
    naturalMetrics: ['reps', 'weight'],
    tags: ['compound'],
  },
  {
    id: 'chinup',
    name: 'Dominadas supinas (chin-up)',
    aliases: ['chin-up', 'chinup'],
    disciplines: ['calisthenics', 'strength'],
    pattern: 'vertical_pull',
    primaryMuscles: ['biceps', 'back_lats'],
    secondaryMuscles: ['forearms'],
    equipment: ['pull_up_bar'],
    minLevel: 'intermediate',
    naturalMetrics: ['reps'],
  },
  {
    id: 'banded_pullup',
    name: 'Dominadas con banda',
    aliases: ['banded pull-up', 'assisted pullup'],
    disciplines: ['calisthenics'],
    pattern: 'vertical_pull',
    primaryMuscles: ['back_lats'],
    secondaryMuscles: ['biceps'],
    equipment: ['pull_up_bar', 'resistance_bands'],
    minLevel: 'beginner',
    progressions: ['pullup'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'negative_pullup',
    name: 'Negativos de dominada',
    aliases: ['negative pull-up'],
    disciplines: ['calisthenics'],
    pattern: 'vertical_pull',
    primaryMuscles: ['back_lats', 'biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['pull_up_bar'],
    minLevel: 'beginner',
    progressions: ['pullup'],
    naturalMetrics: ['reps', 'time'],
  },
  {
    id: 'weighted_pullup',
    name: 'Dominadas con lastre',
    aliases: ['weighted pull-up'],
    disciplines: ['calisthenics', 'strength'],
    pattern: 'vertical_pull',
    primaryMuscles: ['back_lats'],
    secondaryMuscles: ['biceps'],
    equipment: ['pull_up_bar'],
    minLevel: 'advanced',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'lat_pulldown',
    name: 'Jalón al pecho',
    aliases: ['lat pulldown'],
    disciplines: ['strength'],
    pattern: 'vertical_pull',
    primaryMuscles: ['back_lats'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable', 'machine'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },

  // ======== SQUAT ========
  {
    id: 'back_squat',
    name: 'Sentadilla con barra (back squat)',
    aliases: ['back squat', 'barbell squat', 'sentadilla'],
    disciplines: ['strength'],
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'hamstrings', 'back_lower'],
    equipment: ['barbell_plates'],
    minLevel: 'intermediate',
    progressions: ['front_squat'],
    regressions: ['goblet_squat', 'bodyweight_squat'],
    contraindications: ['knee_pain', 'lower_back_pain'],
    naturalMetrics: ['weight', 'reps', 'rir'],
    tags: ['compound', 'main_lift'],
    cue: 'Tórax arriba, rodillas siguiendo punta del pie, talón pegado al suelo.',
  },
  {
    id: 'front_squat',
    name: 'Sentadilla frontal',
    aliases: ['front squat'],
    disciplines: ['strength'],
    pattern: 'squat',
    primaryMuscles: ['quads', 'core'],
    secondaryMuscles: ['glutes', 'back_upper'],
    equipment: ['barbell_plates'],
    minLevel: 'intermediate',
    naturalMetrics: ['weight', 'reps', 'rir'],
  },
  {
    id: 'goblet_squat',
    name: 'Sentadilla goblet',
    aliases: ['goblet squat'],
    disciplines: ['strength'],
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbells', 'kettlebell'],
    minLevel: 'beginner',
    progressions: ['back_squat'],
    naturalMetrics: ['weight', 'reps'],
    tags: ['compound', 'home_friendly'],
  },
  {
    id: 'bodyweight_squat',
    name: 'Sentadilla con peso corporal',
    aliases: ['bodyweight squat', 'air squat'],
    disciplines: ['calisthenics', 'strength', 'mobility'],
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    minLevel: 'beginner',
    progressions: ['goblet_squat', 'pistol_squat'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'pistol_squat',
    name: 'Sentadilla pistol',
    aliases: ['pistol squat'],
    disciplines: ['calisthenics'],
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'hip_flexors'],
    equipment: ['bodyweight'],
    minLevel: 'advanced',
    regressions: ['split_squat'],
    naturalMetrics: ['reps'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Sentadilla búlgara',
    aliases: ['bulgarian split squat', 'rear foot elevated split squat'],
    disciplines: ['strength'],
    pattern: 'lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbells', 'bench'],
    minLevel: 'intermediate',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'split_squat',
    name: 'Split squat',
    aliases: ['split squat'],
    disciplines: ['strength'],
    pattern: 'lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight', 'dumbbells'],
    minLevel: 'beginner',
    progressions: ['bulgarian_split_squat'],
    naturalMetrics: ['reps', 'weight'],
  },
  {
    id: 'walking_lunge',
    name: 'Zancadas caminando',
    aliases: ['walking lunge'],
    disciplines: ['strength'],
    pattern: 'lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['bodyweight', 'dumbbells'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'weight'],
  },
  {
    id: 'leg_press',
    name: 'Prensa de pierna',
    aliases: ['leg press'],
    disciplines: ['strength'],
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['machine'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'leg_extension',
    name: 'Extensión de cuádriceps',
    aliases: ['leg extension'],
    disciplines: ['strength'],
    pattern: 'isolation',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
    tags: ['isolation'],
  },

  // ======== HINGE ========
  {
    id: 'deadlift',
    name: 'Peso muerto convencional',
    aliases: ['deadlift', 'conventional deadlift'],
    disciplines: ['strength'],
    pattern: 'hinge',
    primaryMuscles: ['back_lower', 'glutes', 'hamstrings'],
    secondaryMuscles: ['back_lats', 'forearms', 'core'],
    equipment: ['barbell_plates'],
    minLevel: 'intermediate',
    progressions: ['deficit_deadlift'],
    regressions: ['romanian_deadlift', 'kb_deadlift'],
    contraindications: ['lower_back_pain'],
    naturalMetrics: ['weight', 'reps', 'rir'],
    tags: ['compound', 'main_lift'],
    cue: 'Barra pegada al cuerpo, hombros sobre la barra, empuja el suelo con los talones.',
  },
  {
    id: 'romanian_deadlift',
    name: 'Peso muerto rumano',
    aliases: ['romanian deadlift', 'rdl'],
    disciplines: ['strength'],
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back_lower'],
    equipment: ['barbell_plates', 'dumbbells'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
    cue: 'Cadera atrás, espalda neutra, barra rozando los muslos.',
  },
  {
    id: 'kb_deadlift',
    name: 'Peso muerto con kettlebell',
    aliases: ['kettlebell deadlift'],
    disciplines: ['strength'],
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes', 'back_lower'],
    secondaryMuscles: ['core'],
    equipment: ['kettlebell'],
    minLevel: 'beginner',
    progressions: ['kb_swing', 'deadlift'],
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'kb_swing',
    name: 'Kettlebell swing',
    aliases: ['kettlebell swing', 'swing'],
    disciplines: ['strength'],
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['back_lower', 'core', 'shoulders_front'],
    equipment: ['kettlebell'],
    minLevel: 'beginner',
    naturalMetrics: ['reps', 'weight', 'time'],
    tags: ['power', 'conditioning'],
  },
  {
    id: 'good_morning',
    name: 'Good morning',
    aliases: ['good morning'],
    disciplines: ['strength'],
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'back_lower'],
    secondaryMuscles: ['glutes'],
    equipment: ['barbell_plates'],
    minLevel: 'intermediate',
    contraindications: ['lower_back_pain'],
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'hip_thrust',
    name: 'Hip thrust',
    aliases: ['hip thrust'],
    disciplines: ['strength'],
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['barbell_plates', 'bench'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'glute_bridge',
    name: 'Puente de glúteos',
    aliases: ['glute bridge'],
    disciplines: ['strength', 'mobility'],
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['bodyweight', 'yoga_mat'],
    minLevel: 'beginner',
    progressions: ['hip_thrust'],
    naturalMetrics: ['reps', 'time'],
  },

  // ======== ARM ISOLATION ========
  {
    id: 'biceps_curl',
    name: 'Curl de bíceps con mancuerna',
    aliases: ['biceps curl', 'dumbbell curl'],
    disciplines: ['strength'],
    pattern: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbells'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
    tags: ['isolation'],
  },
  {
    id: 'hammer_curl',
    name: 'Curl martillo',
    aliases: ['hammer curl'],
    disciplines: ['strength'],
    pattern: 'isolation',
    primaryMuscles: ['biceps', 'forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbells'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'triceps_pushdown',
    name: 'Extensiones de tríceps en polea',
    aliases: ['triceps pushdown'],
    disciplines: ['strength'],
    pattern: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },
  {
    id: 'overhead_triceps_ext',
    name: 'Extensión de tríceps por encima de la cabeza',
    aliases: ['overhead triceps extension'],
    disciplines: ['strength'],
    pattern: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbells', 'cable'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'reps'],
  },

  // ======== CARRIES ========
  {
    id: 'farmers_walk',
    name: 'Paseo del granjero',
    aliases: ["farmer's walk", 'farmers walk'],
    disciplines: ['strength'],
    pattern: 'carry',
    primaryMuscles: ['forearms', 'core', 'back_upper'],
    secondaryMuscles: ['glutes', 'quads'],
    equipment: ['dumbbells', 'kettlebell'],
    minLevel: 'beginner',
    naturalMetrics: ['weight', 'distance', 'time'],
    tags: ['conditioning', 'grip'],
  },
];
